name = "0xkai/mint-token"
version = "0.0.0"
compiler = "v1.0.26-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project '0xkai/mint-token'"

[repository]
user = "0xkai"
project = "mint-token"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"

[config]
